script: "bin/rake --trace 2>&1"
bundler_args: "--binstubs --without documentation"
before_install:
  - gem update --system 2.1.11
  - gem --version
  - gem install bundler
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
env:
  - RAILS_VERSION=master
  - RAILS_VERSION=4-2-stable
  - RAILS_VERSION=4-1-stable
  - RAILS_VERSION=4-0-stable
  - RAILS_VERSION=3-2-stable
  - RAILS_VERSION=3.1.12
  - RAILS_VERSION=3.0.20
matrix:
  exclude:
    # MRI 2.2 is not supported on a few versions
    - rvm: 2.2
      env: RAILS_VERSION=3.1.12
    - rvm: 2.2
      env: RAILS_VERSION=3.0.20
    # 3.0.x is not supported on MRI 2.0.0
    - rvm: 2.0.0
      env: RAILS_VERSION=3.0.20
    # 3.0.x is not supported on MRI 2.1.0
    - rvm: 2.1.0
      env: RAILS_VERSION=3.0.20
    # 4.0.x is not supported on MRI 1.8.7 or 1.9.2
    - rvm: 1.8.7
      env: RAILS_VERSION=master
    - rvm: 1.9.2
      env: RAILS_VERSION=master
    - rvm: 1.8.7
      env: RAILS_VERSION=4-2-stable
    - rvm: 1.8.7
      env: RAILS_VERSION=4-1-stable
    - rvm: 1.8.7
      env: RAILS_VERSION=4-0-stable
    - rvm: 1.9.2
      env: RAILS_VERSION=4-2-stable
    - rvm: 1.9.2
      env: RAILS_VERSION=4-1-stable
    - rvm: 1.9.2
      env: RAILS_VERSION=4-0-stable
    - rvm: 1.8.7
      env: RAILS_VERSION=4.0.2
    - rvm: 1.9.2
      env: RAILS_VERSION=4.0.2
  allow_failures:
    - env: RAILS_VERSION=master
